### ISSUE TITLE
Кодування бази, файлів і т.д.

### ISSUE THREAD

**Issue by BrunIF** [Drohomiretskiy-M/Diplom_project_Drohomiretskiy_M#2]
Кодування потрібно використовувати UTF-8.
Всюди змініть. Щоб не було проблем на різних серверах.

**Comment by Drohomiretskiy-M** [comment]
в мому випадку денвер не хоче працювати з UTF-8

6 грудня 2013 р. 11:26 Igor Bronovskyy notifications@github.com написав:

**Comment by BrunIF** [comment]
Ставте XAMPP http://www.apachefriends.org/ru/xampp.html
