### ISSUE TITLE
UML diagram 

### ISSUE THREAD

**Issue by Drohomiretskiy-M** [Drohomiretskiy-M/Diplom_project_Drohomiretskiy_M#4]
![uml](https://f.cloud.github.com/assets/5483755/2123232/0d4e81f6-9228-11e3-982c-157e65d9e79c.JPG)

**Comment by Drohomiretskiy-M** [comment]
Початковий варіант.

**Comment by BrunIF** [comment]
В таблиці **Група** поле _starosta_ потрібно назвати _id_starosta_. Це означає, що воно зв’язано з таблицею **Староста** та полем _id_. 
Думаю, що логіку вловили. Це підхід до назв таблиць і полів.
Тепер по таблиці. Для чого робити таблиці **Викладач** та **Староста**?
Я б зробив таблицю **Персона** в якої була б приналежність до групи (у студентів) чи кафедри (у викладачів). Так буде універсальніше. 
Будете мати час - почитаєте основи нормалізації таблиць. Без заглиблень. ;) 

Чекаю правки і переходимо до інтерфейсу.
